### ISSUE TITLE
Add `--restart unless-stopped` to container runs

### ISSUE THREAD

**Issue by werkt** [80degreeswest/bfmgr#8]
The aws config you're presenting is not resilient to container shutdowns. I just assisted a user whose worker had been interrupted, visible in logs when we looked at inactive containers, and there was no clear indication that his worker wasn't functioning as expected. I recommend you add `--restart unless-stopped` to give folks a fighting chance at seeing their workers survive such a shutdown.

Hopefully this will get the container restarted with all the correct configs, and obviously this needs to play nice with an intentional shutdown, so hopefully the stop flag will get triggered in such an event, or there's something persistent that indicates the worker had been [gracefully] asked to stop.

**Comment by 80degreeswest** [comment]
Fixed in v1.0.15
